# Generated by Django 5.2.6 on 2025-10-01 14:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, default='Описание в разработке', verbose_name='Подробное описание экскурсии'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=tinymce.models.HTMLField(blank=True, default='Описание в разработке', verbose_name='Краткое описание экскурсии'),
        ),
    ]
