# Generated by Django 5.2.6 on 2025-09-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название экскурсии')),
                ('description_short', models.TextField(blank=True, default='Описание в разработке', verbose_name='Краткое описание экскурсии')),
                ('description_long', models.TextField(blank=True, default='Описание в разработке', verbose_name='Подробное описание экскурсии')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
        ),
    ]
